# Project-wide Gradle settings.

# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the
# command line, check build.gradle for more details.

# For more details on how to configure your build environment visit
# http://www.gradle.org/guide/more/customize_gradle_builds

# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for headless machines. See also
# http://gradle.org/guide/more/customize_gradle_builds
# org.gradle.jvmargs=-Xmx1024m -XX:MaxPermSize=256m

# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. See also
# http://gradle.org/guide/more/customize_gradle_builds
# org.gradle.parallel=true

# AndroidX package structure to make it easier to discover and migrate existing, old-style packages
android.useAndroidX=true

# Disable the namespace DSL. The value of this property is ignored for AGP 7.1 and above.
android.disableNamespace=false